### ISSUE TITLE
Outward Normal Computation 

### ISSUE THREAD

**Issue by NatalieKubicki1997** [FEDDLib/FEDDLib#14]
In my case I need the outward normals for the boundary integral in the matrix K because of an additional contribution in the stress-divergence formulation to obtain the same boundary outflow condition as for the conventional formulation with the laplacian term.  Therefore I compute the outward normals in the FE_def.hpp file and save it as an attribute of an AssemblyFEElement

**BUT**
We should think about computing the outward normals for each element/ surface element in the Finite-Element class. 
The Problem is that although for an 2D-traingle the nodes are correctly couter-clockwise oriented s.t. we alsways get the outward normal for an edge, for an subelement there is a random orientation s.t. we can not ensure that the normal vector is pointing outwards

**SOLUTION**
We should implement for each triangle the outward normals for the edges and save it then also for an subelement

**Comment by jakne** [comment]
I have a MATLAB script to do this for unstructured tetrahedral meshes (i.e., triangular surface meshes). The mesh must be the discretization of an open, bounded, and connected domain. The algorithm should be independent of the type and dimension of the discretization (triangular, rectangular, tetrahedral, hexagonal, ...), but it does depend on how the element nodes are arranged (e.g., (a,b,c,d) vs. (a,b,d,c) for quadrilaterals). The outward normal is determined without any input from the user by using Gauss's theorem.

Determining the outward normal should be easy to implement if the surface normals are aligned (all outward facing or all inward facing). Creating consistently aligned normals, however, requires a list of neighboring surface elements that (for example in 3D) share an edge.

**Comment by NatalieKubicki1997** [comment]
The possibility for computing the outward normals was implemented by @LeaSassmannshausen and added in the pull request:
https://github.com/FEDDLib/FEDDLib/pull/43
#43 by [LeaSassmannshausen](https://github.com/FEDDLib/FEDDLib/issues?q=is%3Apr+author%3ALeaSassmannshausen) was merged on Apr 22
• [Approved](https://github.com/FEDDLib/FEDDLib/pull/43#partial-pull-merging)
