### ISSUE TITLE
TEKO Preconditioner is not working 

### ISSUE THREAD

**Issue by NatalieKubicki1997** [FEDDLib/FEDDLib#16]
So the Teko preconditioner is not working at the moment for my problem but maybe it is also because of the old version which I have of Trilinos

**Comment by LeaSassmannshausen** [comment]
@NatalieKubicki1997 Can you post your error message or elaborate on what is not working exactly. Thanks!

**Comment by NatalieKubicki1997** [comment]
In future write more complete update and also write everything down that was discussed in person to understand solution process of this issue
