### ISSUE TITLE
Testing environment 

### ISSUE THREAD

**Issue by NatalieKubicki1997** [FEDDLib/FEDDLib#18]
The future goal should be to run regular, automated (unit) tests on the code to verify that it works correctly.

**Comment by LeaSassmannshausen** [comment]
@NatalieKubicki1997 this is a great idea. 
As a first step, the previous test folder was separated into tests and examples whereas the test folder currently now only includes AceGEN-Interface related tests, but can be extended to more general tests for assembly- and solver routines.

**Comment by NatalieKubicki1997** [comment]
See @24 and @23 (Auto Testing / unit testing)

**Comment by NatalieKubicki1997** [comment]
See other issues
