### ISSUE TITLE
Volume Flag for Meshes

### ISSUE THREAD

**Issue by LeaSassmannshausen** [FEDDLib/FEDDLib#6]
The Volume Flag is limited in most cases by default to 10 (flag for element and interior nodes) . This can cause concrete errors with the program failing or simply lead to faulty flag settings if more than 9 different flags are used. Needs to be fixed.
(Caution!! The flag setting process depends on certain structure. If a node can have more than one flags, the lesser one is chosen.)

**Comment by NatalieKubicki1997** [comment]
This should be now resolved BUT again we need here documentation for starters how the mesh should look like and how Flags should be set e.g regarding the side comment ". If a node can have more than one flags, the lesser one is chosen.)"
